---
functional:
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - На странице корзины пользователь может удалить товар из корзины.
  - На странице корзины пользователь может оформить заказ с переходом на страницу оплаты.
  - Корзина хранится в сессии браузера.
non-functional:
  - Сайт должен быть SPA приложением, которое не перезагружает страницу.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен иметь адаптивную верстку.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - По умолчанию сайт должен открываться на языке, совпадающим с регионом пользователя.
  - Цены по умолчанию должны быть указаны в валюте, совпадающим с регионом пользователя.
  - Должна быть возможность регистрации на сайте.
  - Для зарегистрированных пользователей сохраняется и отображается история заказов.
  - Для пользователя есть форма заполнения контактных данных для оформления заказа.
  - Интернет-магазин поддерживает оплату банковскими картами.
  - Для пользователя есть форма обратной связи при возникновении ошибок и вопросов.
