---
functional:
  - на странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - пользователь должен иметь возможность искать товары по ключевому слову или категории
  - пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д
  - пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - на странице корзины пользователь может удалить товар из корзины
  - на странице корзины пользователь может оформить заказ с переходом на страницу оплаты
  - корзина хранится в сессии браузера
non-functional:
  - сайт должен быть SPA приложением, которое не перезагружает страницу
  - веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен иметь мобильную версию
  - сайт должен иметь адаптивную верстку
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика
  - сайт должен быть доступен на различных устройствах
implicit:
  - по умолчанию сайт должен открываться на языке, совпадающим с регионом пользователя
  - цены по умолчанию должны быть указаны в валюте, совпадающим с регионом пользователя
  - должна быть возможность регистрации на сайте
  - для зарегистрированных пользователей сохраняется и отображается история заказов
  - для пользователей есть форма заполнения контактных данных для оформления заказа
  - интернет-магазин поддерживает оплату банковскими картами
  - для пользователей есть форма обратной связи при возникновении ошибок и вопросов
